---
- name: Manage authorized ssh keys
  authorized_key:
    key: '{{ item.key }}'
    user: '{{ item.user }}'
    exclusive: '{{ item.exclusive|default(authorized_keys__exclusive) }}'
    key_options: '{{ item.key_options|default(omit) }}'
    manage_dir: '{{ item.manage_dir|default(authorized_keys__manage_dir) }}'
    path: '{{ item.path|default(omit) }}'
    state: '{{ "present" if item.disabled is undefined or not item.disabled|bool else "absent" }}'
  with_items:
    - '{{ authorized_keys__list }}'
  when: ((item.key is defined and item.key|trim) and
         (item.user is defined and item.user|trim))
